export const APP_ROUTES = {
  LOGIN: 'login',
  SIGN_UP: 'sign-up',
  DASHBOARD: 'dashboard',
  CURRENTLY_TRADING: 'currently-trading',
  FOLLOWED: 'followed',
  SUGGESTION: 'suggestion',
  SETTING: 'setting',
  SETTING_PROFILE: 'setting/profile',
  SETTING_BINANCE: 'setting/binance',
  SETTING_NOTIFICATION: 'setting/notification',
};

export const APP_PATHS = {
  LOGIN: `/${APP_ROUTES.LOGIN}`,
  SIGN_UP: `/${APP_ROUTES.SIGN_UP}`,
  DASHBOARD: `/${APP_ROUTES.DASHBOARD}`,
  CURRENTLY_TRADING: `/${APP_ROUTES.CURRENTLY_TRADING}`,
  FOLLOWED: `/${APP_ROUTES.FOLLOWED}`,
  SUGGESTION: `/${APP_ROUTES.SUGGESTION}`,
  SETTING: `/${APP_ROUTES.SETTING}`,
  SETTING_PROFILE: `/${APP_ROUTES.SETTING_PROFILE}`,
  SETTING_BINANCE: `/${APP_ROUTES.SETTING_BINANCE}`,
  SETTING_NOTIFICATION: `/${APP_ROUTES.SETTING_NOTIFICATION}`,
};
