import os
import xgboost as xgb
import pandas as pd
import numpy as np
import pandas_ta as ta
import joblib
from sklearn.multioutput import MultiOutputClassifier
from src.core.config import settings
from src.repositories.klines_repository import KlinesFuturesRepository
from src.repositories.training_history_repository import TrainingHistoryRepository
from src.services.binance_service import BinanceService
from src.models.training_history import TrainingHistory
from src.utils.time_utils import get_current_timestamp_ms, get_one_year_ago_timestamp_ms

class XGBoostService:
    def __init__(self,
                 klines_repo: KlinesFuturesRepository,
                 history_repo: TrainingHistoryRepository,
                 binance_service: BinanceService):
        self.klines_repo = klines_repo
        self.history_repo = history_repo
        self.binance_service = binance_service

        # Ensure models directory exists
        os.makedirs(settings.MODELS_DIR, exist_ok=True)

    def _prepare_data(self, klines_dicts, is_training=True):
        # Convert to pandas DataFrame
        df = pd.DataFrame(klines_dicts)

        if df.empty:
            return None, None

        df = df.sort_values('openTime').reset_index(drop=True)

        # Ensure numeric types
        for col in ['open', 'high', 'low', 'close', 'volume']:
            df[col] = df[col].astype(float)

        # Time-based features
        df['datetime'] = pd.to_datetime(df['openTime'], unit='ms')
        df['day_of_week'] = df['datetime'].dt.dayofweek
        df['hour_of_day'] = df['datetime'].dt.hour

        # Simple feature engineering
        df['returns'] = df['close'].pct_change()
        df['volatility'] = df['returns'].rolling(window=20).std()
        df['sma_20'] = df['close'].rolling(window=20).mean()

        # Advanced Technical Indicators using pandas-ta
        df.ta.rsi(length=14, append=True)
        df.ta.macd(fast=12, slow=26, signal=9, append=True)
        df.ta.bbands(length=20, std=2, append=True)
        df.ta.atr(length=14, append=True)

        if is_training:
            # We predict 1-step ahead: next close return and trend
            df['target_trend'] = np.where(df['close'].shift(-1) > df['close'], 1, 0)
            df['target_return'] = df['close'].shift(-1) / df['close'] - 1.0

            # drop the last row as we don't have future data for it
            df = df.iloc[:-1]
        else:
            df['target_trend'] = 0
            df['target_return'] = 0.0

        # Drop NaN generated by rolling windows
        df = df.dropna()

        # Select features
        exclude_cols = ['openTime', 'datetime', 'target_trend', 'target_return']
        features = [col for col in df.columns if col not in exclude_cols]

        X = df[features]
        if is_training:
            y = df[['target_trend', 'target_return']]
        else:
            y = None

        return X, y

    def _klines_to_dicts(self, klines):
        return [{
            'openTime': k.openTime,
            'open': float(k.open),
            'high': float(k.high),
            'low': float(k.low),
            'close': float(k.close),
            'volume': float(k.baseVolume)
        } for k in klines]

    async def train_model(self, symbol: str, interval: str, reset: bool = False):
        history = await self.history_repo.get_latest_history(symbol, interval, 'futures')
        current_time = get_current_timestamp_ms()

        if history and not reset:
            from_time = history.to_time
            to_time = current_time
            is_incremental = True
            model_path = os.path.join(settings.MODELS_DIR, history.file_name)
        else:
            from_time = get_one_year_ago_timestamp_ms()
            to_time = current_time
            is_incremental = False
            file_name = f"{symbol}_{interval}_xgboost.pkl"
            model_path = os.path.join(settings.MODELS_DIR, file_name)

        if from_time >= to_time:
            return {"success": False, "message": "Already up to date."}

        klines = await self.binance_service.get_klines(symbol, interval, from_time, to_time)
        if len(klines) < 50:
            return {"success": False, "message": "Not enough data to train."}

        kline_dicts = self._klines_to_dicts(klines)
        X, y = self._prepare_data(kline_dicts, is_training=True)
        if X is None or len(X) == 0:
            return {"success": False, "message": "Feature engineering failed or insufficient valid data."}

        # Train Classifier (for Trend & Confidence)
        clf = xgb.XGBClassifier(
            n_estimators=200, learning_rate=0.05, max_depth=6,
            subsample=0.8, colsample_bytree=0.8, random_state=42, eval_metric='logloss'
        )
        # Train Regressor (for Price)
        reg = xgb.XGBRegressor(
            n_estimators=200, learning_rate=0.05, max_depth=6,
            subsample=0.8, colsample_bytree=0.8, random_state=42, eval_metric='rmse'
        )

        if is_incremental and os.path.exists(model_path):
            # Retrain on full newly combined dataset
            clf.fit(X, y['target_trend'])
            reg.fit(X, y['target_return'])
            await self.history_repo.update_history(history.id, to_time)
            result_file = history.file_name
        else:
            if history and reset:
                await self.history_repo.delete_history(history.id)
                if os.path.exists(model_path):
                    os.remove(model_path)

            clf.fit(X, y['target_trend'])
            reg.fit(X, y['target_return'])

            new_history = TrainingHistory(
                symbol=symbol, time_frame=interval, from_time=from_time,
                to_time=to_time, file_name=file_name, market_type='futures'
            )
            await self.history_repo.save_history(new_history)
            result_file = file_name

        joblib.dump({'clf': clf, 'reg': reg}, model_path)

        return {
            "success": True, "message": "Model trained successfully.",
            "file_name": result_file, "from_time": from_time,
            "to_time": to_time, "is_incremental": is_incremental
        }

    async def forecast(self, symbol: str, interval: str, quantity: int = 3):
        history = await self.history_repo.get_latest_history(symbol, interval, 'futures')
        if not history:
            return {"success": False, "message": "No trained model found for this symbol and timeframe."}

        model_path = os.path.join(settings.MODELS_DIR, history.file_name)
        if not os.path.exists(model_path):
            return {"success": False, "message": "Model file not found on disk."}

        current_time = get_current_timestamp_ms()
        await self.binance_service.get_klines(symbol, interval, current_time - 1000 * 60 * 60 * 24 * 10, current_time)
        klines = await self.klines_repo.get_klines_in_range(symbol, interval, current_time - 1000 * 60 * 60 * 24 * 10, current_time)

        if len(klines) < 50:
             return {"success": False, "message": "Not enough recent data to forecast."}

        # Filter out forming candle
        if klines[-1].closeTime > current_time:
            klines = klines[:-1]

        kline_dicts = self._klines_to_dicts(klines)
        models = joblib.load(model_path)
        clf = models['clf']
        reg = models['reg']

        interval_ms = kline_dicts[-1]['openTime'] - kline_dicts[-2]['openTime']
        forecasts = []

        # Autoregressive prediction
        for i in range(quantity):
            X, _ = self._prepare_data(kline_dicts, is_training=False)
            if X is None or len(X) == 0:
                break

            latest_features = X.iloc[-1:]

            # Predict Trend & Confidence
            prob = clf.predict_proba(latest_features)[0]
            trend = "UP" if prob[1] > 0.5 else "DOWN"
            confidence = float(prob[1] if trend == "UP" else prob[0])

            # Predict Price
            pred_return = float(reg.predict(latest_features)[0])
            last_close = kline_dicts[-1]['close']
            next_close = last_close * (1.0 + pred_return)

            # Calculate expected min/max range based on historical volatility
            vol = float(latest_features['volatility'].iloc[0])
            price_std = last_close * vol
            min_price = min(last_close, next_close) - price_std
            max_price = max(last_close, next_close) + price_std

            # Next candle's openTime
            next_openTime = int(kline_dicts[-1]['openTime'] + interval_ms)
            
            forecasts.append({
                "openTime": next_openTime,
                "trend": trend,
                "price": round(next_close, 4),
                "min_price": round(min_price, 4),
                "max_price": round(max_price, 4),
                "confidence": round(confidence, 4)
            })

            # Append simulated candle for next iteration
            kline_dicts.append({
                'openTime': next_openTime,
                'open': last_close,
                'high': max_price,
                'low': min_price,
                'close': next_close,
                'volume': kline_dicts[-1]['volume'] # mock volume
            })

        return {
            "success": True,
            "symbol": symbol,
            "timeFrame": interval,
            "quantity": quantity,
            "forecasts": forecasts,
            "message": "Forecast successful."
        }
